SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



CREATE  TABLE IF NOT EXISTS `event` (
  `idevent` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodeevent` VARCHAR(63) NOT NULL ,
  `nomevent` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  PRIMARY KEY (`idevent`,`nomcodeevent`) )
ENGINE = MyISAM;


CREATE  TABLE IF NOT EXISTS `eventexectask` (
  `ideventexectask` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `idevent` BIGINT UNSIGNED NOT NULL DEFAULT '0' ,
  `idtask` BIGINT UNSIGNED NOT NULL ,
  `ordre` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`ideventexectask`) )
ENGINE = MyISAM;


CREATE  TABLE IF NOT EXISTS `task` (
  `idtask` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodetask` VARCHAR(63) NOT NULL ,
  `nomtask` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `typetask` VARCHAR(63) NOT NULL ,
  PRIMARY KEY (`idtask`,`nomcodetask`) )
ENGINE = MyISAM;








SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;