SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



-- tables gestion sharedpackage

CREATE  TABLE IF NOT EXISTS `sharedpackage` (
  `idsharedpackage` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodesharedpackage` VARCHAR(63) NOT NULL ,
  `nomsharedpackage` VARCHAR(255) NULL ,
  `groupe` VARCHAR(255) NULL ,
  `mainimg` VARCHAR(1020) NULL ,
  `datecreate` DATETIME DEFAULT CURRENT_TIMESTAMP ,
  `datemodif` DATETIME ON UPDATE CURRENT_TIMESTAMP ,
  `text` TEXT NULL ,
  `externallink` VARCHAR(1020) NULL ,
  PRIMARY KEY (`idsharedpackage`,`nomcodesharedpackage`) )
ENGINE = MyISAM;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;