SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



-- tables gestion zonegeo

CREATE  TABLE IF NOT EXISTS `zonegeo` (
  `idzonegeo` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodezonegeo` VARCHAR(63) NOT NULL ,
  `nomzonegeo` VARCHAR(255) NULL ,
  `greycode` VARCHAR(255) NULL ,
  `lat` TEXT NULL ,
  `lon` VARCHAR(50) NULL ,
  PRIMARY KEY (`idzonegeo`,`nomcodezonegeo`) )
ENGINE = MyISAM;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;