SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



CREATE  TABLE IF NOT EXISTS `lib` (
  `idlib` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodelib` VARCHAR(63) NOT NULL ,
  `nomlib` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `idlibtype` BIGINT UNSIGNED NOT NULL DEFAULT '1' ,
  PRIMARY KEY (`idlib`,`nomcodelib`) )
ENGINE = MyISAM;


CREATE  TABLE IF NOT EXISTS `chainuselib` (
  `idchainuselib` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `idchain` BIGINT UNSIGNED NOT NULL DEFAULT '0' ,
  `idlib` BIGINT UNSIGNED NOT NULL DEFAULT '0' ,
--  `selected` SMALLINT UNSIGNED NOT NULL DEFAULT '0' , 
  `ordre` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`idchainuselib`) )
ENGINE = MyISAM;


CREATE  TABLE IF NOT EXISTS `libtype` (
  `idlibtype` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodelibtype` VARCHAR(63) NOT NULL ,
  `nomlibtype` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `uniquelib` SMALLINT UNSIGNED NOT NULL DEFAULT '0' ,
  `iddefaultlib` BIGINT UNSIGNED NOT NULL DEFAULT '0' ,
  PRIMARY KEY (`idlibtype`,`nomcodelibtype`) )
ENGINE = MyISAM;


INSERT INTO `libtype` VALUES (NULL, 'other', 'other', 'other') ;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;