SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



-- tables gestion packager

CREATE  TABLE IF NOT EXISTS `optionpackager` (
  `idoptionpackager` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodepackage` VARCHAR(255) NULL ,
  `nomoption` VARCHAR(255) NULL ,
  `option` TEXT NULL ,
  PRIMARY KEY (`idoptionpackager`,`nomcodepackage`,`nomoption`) )
ENGINE = MyISAM;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;