SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';






-- tables gestion token

CREATE  TABLE IF NOT EXISTS `multisite` (
  `idmultisite` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `host` VARCHAR(2050) NULL ,
  `chain` VARCHAR(255) NULL ,
  PRIMARY KEY (`idmultisite`) )
ENGINE = MyISAM;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;