SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



-- tables gestion page

CREATE  TABLE IF NOT EXISTS `page` (
  `idpage` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodepage` VARCHAR(63) NOT NULL ,
  `nompage` VARCHAR(255) NULL ,
  `titre` VARCHAR(255) NULL ,
  `texte` TEXT NULL ,
  PRIMARY KEY (`idpage`,`nomcodepage`) )
ENGINE = MyISAM;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;