SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';



-- tables gestion deployer

CREATE  TABLE IF NOT EXISTS `deployer` (
  `iddeployer` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `nomcodedeployer` VARCHAR(255) NULL ,
  `nomdeployer` VARCHAR(255) NULL ,
  `groupedeployer` VARCHAR(255) NULL ,
  `description` TEXT NULL ,
  `version` VARCHAR(50) NULL ,
  `deployed` INT UNSIGNED NOT NULL ,
  PRIMARY KEY (`idpackage`,`nomcodepackage`) )
ENGINE = MyISAM;





SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;