SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';






-- tables gestion tracker

CREATE  TABLE IF NOT EXISTS `tracker` (
  `idtracker` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT ,
  `lien` VARCHAR(2050) NULL ,
  `date` DATETIME NULL ,
  `iduser` BIGINT UNSIGNED NOT NULL ,
  `lang` VARCHAR(10) NULL DEFAULT 'fr_fr',
  PRIMARY KEY (`idtracker`) )
ENGINE = MyISAM;






SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;